using System.Globalization;
using System.Resources;

namespace AcKrovy.Localization;

public static class UiStrings
{
    private static readonly ResourceManager ResourceManager = new(
        "AcKrovy.Localization.Resources.UiStrings",
        typeof(UiStrings).Assembly);

    public static string ReportTitle => GetString("Report_Title");
    public static string ReportColumnItem => GetString("Report_Column_Item");
    public static string ReportColumnType => GetString("Report_Column_Type");
    public static string ReportColumnMaterial => GetString("Report_Column_Material");
    public static string ReportColumnWidthMm => GetString("Report_Column_WidthMm");
    public static string ReportColumnHeightMm => GetString("Report_Column_HeightMm");
    public static string ReportColumnPieceLengthM => GetString("Report_Column_PieceLengthM");
    public static string ReportColumnCount => GetString("Report_Column_Count");
    public static string ReportColumnTotalLengthM => GetString("Report_Column_TotalLengthM");
    public static string ReportColumnVolumeM3 => GetString("Report_Column_VolumeM3");
    public static string ReportTotalFormat => GetString("Report_TotalFormat");
    public static string MessageDialogTitle => GetString("Message_DialogTitle");
    public static string MessagePluginLoaded =>
        Format(GetString("Message_PluginLoaded"), ApplicationVersionProvider.DisplayVersion);
    public static string HelpCommandOverview =>
        Format(GetString("Help_CommandOverview"), ApplicationVersionProvider.DisplayVersion) +
        GetActiveUiString("Help_CustomCommandLine");
    public static string CommandRibbonReady => GetString("Command_Ribbon_Ready");
    public static string CommandRibbonPending => GetString("Command_Ribbon_Pending");
    public static string CommandToolbarShown => GetString("Command_Toolbar_Shown");
    public static string CommandToolbarHidden => GetString("Command_Toolbar_Hidden");
    public static string CommandSettingsSaveFailedFormat => GetString("Command_Settings_SaveFailedFormat");
    public static string CommandSettingsSaved => GetString("Command_Settings_Saved");
    public static string CommandSettingsPromptApplyAllowances => GetString("Command_Settings_PromptApplyAllowances");
    public static string CommandSettingsSelectionCancelled => GetString("Command_Settings_SelectionCancelled");
    public static string CommandLabelsPromptSelected => GetString("Command_Labels_PromptSelected");
    public static string CommandLabelsUpdatedFormat => GetString("Command_Labels_UpdatedFormat");
    public static string CommandLabelsRefreshFailedFormat => GetString("Command_Labels_RefreshFailedFormat");
    public static string CommandEditPrompt => GetString("Command_Edit_Prompt");
    public static string CommandEditNoData => GetString("Command_Edit_NoData");
    public static string CommandEditTitleSingleFormat => GetString("Command_Edit_TitleSingleFormat");
    public static string CommandEditTitleMultipleFormat => GetString("Command_Edit_TitleMultipleFormat");
    public static string CommandEditResultFormat => GetString("Command_Edit_ResultFormat");
    public static string CommandFlipSlopePrompt => GetString("Command_FlipSlope_Prompt");
    public static string CommandFlipSlopeNotTimberOrAnnotation => GetString("Command_FlipSlope_NotTimberOrAnnotation");
    public static string CommandFlipSlopeHorizontal => GetString("Command_FlipSlope_Horizontal");
    public static string CommandFlipSlopePostPerpendicular => GetString("Command_FlipSlope_PostPerpendicular");
    public static string CommandFlipSlopeResultReversed => GetString("Command_FlipSlope_ResultReversed");
    public static string CommandFlipSlopeResultNormal => GetString("Command_FlipSlope_ResultNormal");
    public static string CommandInspectPrompt => GetActiveUiString("Command_Inspect_Prompt");
    public static string CommandInspectNoData => GetActiveUiString("Command_Inspect_NoData");
    public static string CommandInspectAllowanceDefault => GetActiveUiString("Command_Inspect_AllowanceDefault");
    public static string CommandInspectAllowanceIndividual => GetActiveUiString("Command_Inspect_AllowanceIndividual");
    public static string CommandInspectSummaryFormat => GetActiveUiString("Command_Inspect_SummaryFormat");
    public static string CommandInspectFootprintSummaryFormat => GetActiveUiString("Command_Inspect_FootprintSummaryFormat");
    public static string DialogInspectItem => GetActiveUiString("Dialog_Inspect_Item");
    public static string DialogInspectElementType => GetActiveUiString("Dialog_Inspect_ElementType");
    public static string DialogInspectMaterial => GetActiveUiString("Dialog_Inspect_Material");
    public static string DialogInspectWidth => GetActiveUiString("Dialog_Inspect_Width");
    public static string DialogInspectHeight => GetActiveUiString("Dialog_Inspect_Height");
    public static string DialogInspectSlope => GetActiveUiString("Dialog_Inspect_Slope");
    public static string DialogInspectSlopeDirection => GetActiveUiString("Dialog_Inspect_SlopeDirection");
    public static string DialogInspectPlanLength => GetActiveUiString("Dialog_Inspect_PlanLength");
    public static string DialogInspectActualLength => GetActiveUiString("Dialog_Inspect_ActualLength");
    public static string DialogInspectCuttingAllowance => GetActiveUiString("Dialog_Inspect_CuttingAllowance");
    public static string DialogInspectCuttingLength => GetActiveUiString("Dialog_Inspect_CuttingLength");
    public static string DialogInspectManualLengthMode => GetActiveUiString("Dialog_Inspect_ManualLengthMode");
    public static string DialogInspectCadHandle => GetActiveUiString("Dialog_Inspect_CadHandle");
    public static string DialogInspectManualLength => GetActiveUiString("Dialog_Inspect_ManualLength");
    public static string MessageYes => GetString("Message_Yes");
    public static string MessageNo => GetString("Message_No");
    public static string MessageDirectionNormal => GetString("Message_DirectionNormal");
    public static string MessageDirectionReversed => GetString("Message_DirectionReversed");
    public static string CommandReportPromptSelection => GetString("Command_Report_PromptSelection");
    public static string CommandReportNoneFound => GetString("Command_Report_NoneFound");
    public static string CommandReportElementSkippedFormat => GetString("Command_Report_ElementSkippedFormat");
    public static string CommandReportNoValidElements => GetString("Command_Report_NoValidElements");
    public static string CommandReportPromptInsertionPoint => GetString("Command_Report_PromptInsertionPoint");
    public static string CommandReportInsertedFormat => GetString("Command_Report_InsertedFormat");
    public static string CommandRecalcElementErrorFormat => GetString("Command_Recalc_ElementErrorFormat");
    public static string CommandRecalcResultFormat => GetString("Command_Recalc_ResultFormat");
    public static string CommandRenumberConfirmPrompt => GetString("Command_Renumber_ConfirmPrompt");
    public static string CommandRenumberNoElements => GetString("Command_Renumber_NoElements");
    public static string CommandRenumberResultFormat => GetString("Command_Renumber_ResultFormat");
    public static string CommandRenumberFailedFormat => GetString("Command_Renumber_FailedFormat");
    public static string CommandAssignPrompt => GetString("Command_Assign_Prompt");
    public static string CommandAssignPromptTypeFormat => GetString("Command_Assign_PromptTypeFormat");
    public static string CommandAssignResultFormat => GetString("Command_Assign_ResultFormat");
    public static string CommandPostFootprintEdgePrompt => GetActiveUiString("Command_PostFootprint_EdgePrompt");
    public static string CommandPostFootprintPolylineOnly => GetActiveUiString("Command_PostFootprint_PolylineOnly");
    public static string CommandPostFootprintInvalidGeometry => GetActiveUiString("Command_PostFootprint_InvalidGeometry");
    public static string CommandPostFootprintAmbiguousPick => GetActiveUiString("Command_PostFootprint_AmbiguousPick");
    public static string CommandPostFootprintPickTooFar => GetActiveUiString("Command_PostFootprint_PickTooFar");
    public static string CommandPostFootprintAssignRedirect => GetActiveUiString("Command_PostFootprint_AssignRedirect");
    public static string CommandPostFootprintAssignedFormat => GetActiveUiString("Command_PostFootprint_AssignedFormat");
    public static string CommandPostFootprintLineNotFound => GetActiveUiString("Command_PostFootprint_LineNotFound");
    public static string CommandPostFootprintLineAmbiguous => GetActiveUiString("Command_PostFootprint_LineAmbiguous");
    public static string CommandPostFootprintLineBranching => GetActiveUiString("Command_PostFootprint_LineBranching");
    public static string CommandPostFootprintLineNotRectangle => GetActiveUiString("Command_PostFootprint_LineNotRectangle");
    public static string CommandPostFootprintLineDuplicate => GetActiveUiString("Command_PostFootprint_LineDuplicate");
    public static string CommandPostFootprintUnsupportedPlane => GetActiveUiString("Command_PostFootprint_UnsupportedPlane");
    public static string CommandLayersElementSkippedFormat => GetString("Command_Layers_ElementSkippedFormat");
    public static string CommandLayersResultFormat => GetString("Command_Layers_ResultFormat");
    public static string CommandSettingsApplyElementSkippedFormat => GetString("Command_Settings_ApplyElementSkippedFormat");
    public static string CommandSettingsApplyResultFormat => GetString("Command_Settings_ApplyResultFormat");
    public static string CommandLabelsShown => GetString("Command_Labels_Shown");
    public static string CommandLabelsHidden => GetString("Command_Labels_Hidden");
    public static string CommandLabelsLayerMissing => GetString("Command_Labels_LayerMissing");
    public static string CommandPromptRemoveSelection => GetString("Command_Prompt_RemoveSelection");
    public static string WarningLiveRefreshSkippedFormat => GetString("Warning_LiveRefreshSkippedFormat");
    public static string DialogEditFieldWidth => GetString("Dialog_Edit_FieldWidth");
    public static string DialogEditFieldHeight => GetString("Dialog_Edit_FieldHeight");
    public static string DialogEditFieldCuttingAllowance => GetString("Dialog_Edit_FieldCuttingAllowance");
    public static string DialogEditFieldManualLength => GetString("Dialog_Edit_FieldManualLength");
    public static string DialogEditWholeNonnegativeFormat => GetString("Dialog_Edit_WholeNonnegativeFormat");
    public static string DialogEditPositiveNumberFormat => GetString("Dialog_Edit_PositiveNumberFormat");
    public static string DialogLayersErrorFormat => GetString("Dialog_Layers_ErrorFormat");
    public static string DialogLayersDuplicateFormat => GetString("Dialog_Layers_DuplicateFormat");
    public static string DialogSettingsRoundingStepFormat => GetString("Dialog_Settings_RoundingStepFormat");
    public static string DialogSettingsCuttingAllowanceFormat => GetString("Dialog_Settings_CuttingAllowanceFormat");
    public static string ErrorLayerNameEmpty => GetString("Error_LayerName_Empty");
    public static string ErrorLayerNameTooLong => GetString("Error_LayerName_TooLong");
    public static string ErrorLayerNameInvalidCharacter => GetString("Error_LayerName_InvalidCharacter");
    public static string EditWindowTitle => GetString("EditWindow_Title");
    public static string EditWindowHeading => GetString("EditWindow_Heading");
    public static string EditWindowElementType => GetString("EditWindow_ElementType");
    public static string EditWindowWidthMm => GetString("EditWindow_WidthMm");
    public static string EditWindowHeightMm => GetString("EditWindow_HeightMm");
    public static string EditWindowSlopeDegrees => GetString("EditWindow_SlopeDegrees");
    public static string EditWindowSlopeDirection => GetString("EditWindow_SlopeDirection");
    public static string EditWindowRoofPlane => GetString("EditWindow_RoofPlane");
    public static string EditWindowCuttingAllowanceMm => GetString("EditWindow_CuttingAllowanceMm");
    public static string EditWindowUseDefaultByType => GetString("EditWindow_UseDefaultByType");
    public static string EditWindowLengthMode => GetString("EditWindow_LengthMode");
    public static string EditWindowManualLengthMm => GetString("EditWindow_ManualLengthMm");
    public static string EditWindowMaterial => GetString("EditWindow_Material");
    public static string EditWindowChangeTooltip => GetString("EditWindow_ChangeTooltip");
    public static string EditWindowCancel => GetString("EditWindow_Cancel");
    public static string EditWindowApply => GetString("EditWindow_Apply");
    public static string EditWindowSlopeDirectionNormal => GetString("EditWindow_SlopeDirectionNormal");
    public static string EditWindowSlopeDirectionReversed => GetString("EditWindow_SlopeDirectionReversed");
    public static string EditWindowSlopeDirectionMixedTooltip => GetString("EditWindow_SlopeDirectionMixedTooltip");
    public static string EditWindowCuttingAllowanceMixedTooltip => GetString("EditWindow_CuttingAllowanceMixedTooltip");
    public static string EditWindowDefaultAllowanceTooltip => GetString("EditWindow_DefaultAllowanceTooltip");
    public static string SettingsWindowTitle => GetString("SettingsWindow_Title");
    public static string SettingsWindowHeading => GetString("SettingsWindow_Heading");
    public static string SettingsWindowDescription => GetString("SettingsWindow_Description");
    public static string SettingsWindowLayersTab => GetString("SettingsWindow_Layers_Tab");
    public static string SettingsWindowLayersElementTypeColumn => GetString("SettingsWindow_Layers_ElementTypeColumn");
    public static string SettingsWindowLayersLayerNameColumn => GetString("SettingsWindow_Layers_LayerNameColumn");
    public static string SettingsWindowLayersLayerColorColumn => GetString("SettingsWindow_Layers_LayerColorColumn");
    public static string SettingsWindowManufacturingTab => GetString("SettingsWindow_Manufacturing_Tab");
    public static string SettingsWindowManufacturingDescription => GetString("SettingsWindow_Manufacturing_Description");
    public static string SettingsWindowManufacturingRoundingStep => GetString("SettingsWindow_Manufacturing_RoundingStep");
    public static string SettingsWindowManufacturingElementTypeColumn => GetString("SettingsWindow_Manufacturing_ElementTypeColumn");
    public static string SettingsWindowManufacturingDefaultAllowanceColumn => GetString("SettingsWindow_Manufacturing_DefaultAllowanceColumn");
    public static string SettingsWindowLanguageTab => GetString("SettingsWindow_Language_Tab");
    public static string SettingsWindowLanguageDescription => GetString("SettingsWindow_Language_Description");
    public static string SettingsWindowLanguageLabel => GetString("SettingsWindow_Language_Label");
    public static string SettingsWindowRestoreDefaults => GetString("SettingsWindow_RestoreDefaults");
    public static string SettingsWindowCancel => GetString("SettingsWindow_Cancel");
    public static string SettingsWindowSave => GetString("SettingsWindow_Save");
    public static string SettingsWindowSaveNewElementsOnly => GetString("SettingsWindow_SaveNewElementsOnly");
    public static string SettingsWindowSaveApplySelection => GetString("SettingsWindow_SaveApplySelection");
    public static string SettingsWindowSaveApplyAll => GetString("SettingsWindow_SaveApplyAll");
    public static string LayerColorRed => GetString("LayerColor_Red");
    public static string LayerColorYellow => GetString("LayerColor_Yellow");
    public static string LayerColorGreen => GetString("LayerColor_Green");
    public static string LayerColorCyan => GetString("LayerColor_Cyan");
    public static string LayerColorBlue => GetString("LayerColor_Blue");
    public static string LayerColorMagenta => GetString("LayerColor_Magenta");
    public static string LayerColorOrange => GetString("LayerColor_Orange");
    public static string LayerColorGray => GetString("LayerColor_Gray");
    public static string LayerColorLightGray => GetString("LayerColor_LightGray");
    public static string InspectWindowTitle => GetString("InspectWindow_Title");
    public static string InspectWindowHeading => GetString("InspectWindow_Heading");
    public static string InspectWindowClose => GetString("InspectWindow_Close");
    public static string RibbonTabTitle => GetString("Ribbon_Tab_Title");
    public static string RibbonPanelElements => GetString("Ribbon_Panel_Elements");
    public static string RibbonPanelData => GetString("Ribbon_Panel_Data");
    public static string RibbonPanelReports => GetString("Ribbon_Panel_Reports");
    public static string RibbonPanelSettings => GetString("Ribbon_Panel_Settings");
    public static string RibbonPanelLabels => GetString("Ribbon_Panel_Labels");
    public static string RibbonPanelToolbar => GetString("Ribbon_Panel_Toolbar");
    public static string ToolbarTitle => GetString("Toolbar_Title");
    public static string ToolbarContentTitle => GetString("Toolbar_ContentTitle");
    public static string ErrorNoActiveDrawing => GetString("Error_NoActiveDrawing");
    public static string ErrorUnsupportedTimberGeometry => GetString("Error_UnsupportedTimberGeometry");
    public static string ErrorLabelUnsupportedEntityType => GetString("Error_LabelUnsupportedEntityType");
    public static string ErrorXDataTooLargeFormat => GetString("Error_XDataTooLargeFormat");
    public static string ErrorSlopeAnnotationUnsupportedEntityType => GetString("Error_SlopeAnnotationUnsupportedEntityType");
    public static string ErrorUnsupportedSlopeGlyph => GetString("Error_UnsupportedSlopeGlyph");
    public static string ErrorInvalidElementLayerFormat => GetString("Error_InvalidElementLayerFormat");
    public static string ErrorInvalidAnnotationLayerFormat => GetString("Error_InvalidAnnotationLayerFormat");
    public static string ErrorInvalidSlopeDegrees => GetString("Error_InvalidSlopeDegrees");
    public static string ErrorRenumberEntityUnavailable => GetString("Error_Renumber_EntityUnavailable");

    public static string Format(string format, params object?[] arguments) =>
        string.Format(CultureInfo.CurrentCulture, format, arguments);

    public static string GetString(string resourceKey, CultureInfo? culture = null) =>
        ResourceManager.GetString(resourceKey, culture ?? AppLanguageService.CurrentUiCulture) ?? resourceKey;

    private static string GetActiveUiString(string resourceKey) =>
        GetString(resourceKey, UiStringBindingSource.Shared.Culture);
}
